apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: bretfisher/examplevotingapp_worker:latest
          name: worker
          command: ["sleep"]
          args: ["infinity"]
